services:
  ldap:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "1389:1389"
  mc:
    image: itzg/minecraft-server:20200320
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: CUSTOM
      JVM_OPTS: "-Dcom.sun.jndi.ldap.object.trustURLCodebase=true"
      CUSTOM_SERVER: minecraft_server.jar

    volumes:
      - ./minecraft:/data